### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by TheSeubert** [comment]
Thanks for the PR @shortdudey123. Reading over, the changes look great. I am running through test locally now and can provide more feedback afterwards.

From a standards approach we are lacking a lot here, so I would like to see us update this with CircleCI as well.

**Comment by shortdudey123** [comment]
> so I would like to see us update this with CircleCI as well.

Sure, i can add Circle.  Normally I use travis, but i can add a `circle.yml` file instead :)

For the most part, the changes are testing and syntax, however, i did fix a bug with https://github.com/shortdudey123/chef-slack_handler/commit/b93af6056681b9f880a108166b7f10766e36006d

**Comment by TheSeubert** [comment]
No worries that is something we will add afterwards.

**Comment by martinb3** [comment]
These test suites all converged & verified for me. :+1:

**Pull request merged**
